name = "Effects"
uuid = "3e3a404a-581f-45b1-b240-9020901d6d43"
authors = ["Mike J Innes <mike.j.innes@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
